---

- name: all tasks run as virt_user
  become: yes
  become_user: "{{ virt_user }}"
  block:
    - name: define nodes
      tags:
        - libvirt
        - domains
      virt:
        name: "{{ item.name }}"
        command: define
        xml: "{{ lookup('template', 'domain.xml.j2') }}"
        uri: "qemu:///system"
      loop: "{{ vms }}"

    - name: start domains
      tags:
        - libvirt
        - domains
        - start-domains
      virt:
        name: "{{ item.name }}"
        state: running
        uri: "qemu:///system"
      loop: "{{ vms }}"
      when:
        - item.autostart is defined
        - item.autostart
