---
- name: common tags
  tags:
    - libvirt
    - config
    - builder-bootstrap
  block:
    - name: create virt_user
      user:
        comment: "Virtual user for tripleo lab"
        create_home: yes
        generate_ssh_key: yes
        groups:
          - libvirt
          - kvm
          - qemu
        home: "{{basedir}}"
        name: "{{virt_user}}"
        shell: "/bin/bash"
        ssh_key_bits: 4096
        state: present

    - name: set virt_user home rights
      file:
        state: directory
        path: "{{basedir}}"
        mode: 0750
        group: qemu

    - name: push authorized_keys
      copy:
        src: /root/.ssh/authorized_keys
        remote_src: yes
        dest: "{{basedir}}/.ssh/authorized_keys"
        group: "{{virt_user}}"
        mode: 0600
        owner: "{{virt_user}}"

    - name: push polkit config
      template:
        dest: /etc/polkit-1/rules.d/50-org.libvirt.unix.manage.rules
        src: "50-org.libvirt.unix.manage.rules.j2"
        group: root
        mode: 0644
        owner: root
        serole: object_r
        setype: etc_t
        seuser: system_u

- name: run tasks as virt_user user
  become: yes
  become_user: "{{ virt_user }}"
  tags:
    - lab
  block:
    - name: export LIBVIRT_DEFAULT_URI
      lineinfile:
        path: "{{basedir}}/.bashrc"
        line: "export LIBVIRT_DEFAULT_URI='qemu:///system'"

    - name: create some directories
      tags:
        - config
      file:
        state: directory
        group: qemu
        path: "{{basedir}}/{{item}}"
        mode: 02770
      with_items:
        - images
        - workload
        - configs

    - name: fetch centos base image
      tags:
        - images
      get_url:
        url: "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
        dest: "{{basedir}}/images/centos-7.qcow2"
        mode: 0664

    - name: create images based on centos
      when:
        base_image == "centos"
      tags:
        - images
      command: |
        qemu-img create -o backing_file=../images/centos-7.qcow2,backing_fmt=qcow2 -f qcow2 "{{item.name}}".qcow2 100G
      args:
        creates: "{{basedir}}/workload/{{item.name}}.qcow2"
        chdir: "{{basedir}}/workload"
      loop: "{{vms}}"
      loop_control:
        label: "{{item.name}}"

    - name: create images based on RHEL
      when:
        base_image == "rhel"
      tags:
        - images
      command: |
        qemu-img create -o backing_file=../images/redhat-7.qcow2,backing_fmt=qcow2 -f qcow2 "{{item.name}}".qcow2 100G
      args:
        creates: "{{basedir}}/workload/{{item.name}}.qcow2"
        chdir: "{{basedir}}/workload"
      loop: "{{vms}}"
      loop_control:
        label: "{{item.name}}"

    - name: create swap files when needed
      tags:
        - images
      command: "qemu-img create -f raw {{item.name}}-swap.img {{item.swap}}"
      when:
        - item.swap is defined
      args:
        creates: "{{basedir}}/workload/{{item.name}}-swap.img"
        chdir: "{{basedir}}/workload"
      loop: "{{vms}}"
      loop_control:
        label: "{{item.name}}"

    - name: push proxy config id needed
      template:
        dest: "{{basedir}}/configs/http_proxy.sh"
        src: http_proxy.j2
      when:
        - proxy_host is defined
