---
- name: common tags
  tags:
    - builder-packages
    - builder-bootstrap
  block:
    - name: install rdo-trunk deps
      get_url:
        url: https://trunk.rdoproject.org/centos7-master/rdo-trunk-runtime-deps.repo
        dest: /etc/yum.repos.d/rdo-trunk-runtime-deps.repo

    - name: install delorean
      get_url:
        url: https://trunk.rdoproject.org/centos7-master/puppet-passed-ci/delorean.repo
        dest: /etc/yum.repos.d/delorean.repo

    - name: ensure packages are present
      package:
        name: "{{item}}"
        state: present
      with_items:
        - bash-completion
        - docker
        - libguestfs-tools
        - libvirt
        - libvirt-client
        - libvirt-daemon
        - libvirt-daemon-kvm
        - python2-setuptools
        - python2-virtualbmc
        - tmux
        - vim
