---
- name: ensure packages are present
  package:
    name: "{{item}}"
    state: present
  with_items:
    - docker
    - libguestfs-tools
    - libvirt
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-kvm
    - screen
    - tmux
    - vim

- name: ensure services are loaded and active
  service:
    enabled: yes
    name: "{{item}}"
    state: started
  with_items:
    - libvirtd
    - docker
