---
- name: push helper scripts
  tags:
    - config
    - scripts
  copy:
    dest: "/usr/local/bin/{{item}}"
    group: root
    mode: 0755
    owner: root
    src: "../files/scripts/{{item}}"
  loop:
    - lab-helpers
    - lab-snapshot
    - lab-start
    - lab-stop

- name: push lab-destroy template
  tags:
    - config
    - scripts
  template:
    dest: /usr/local/bin/lab-destroy
    group: root
    mode: 0755
    owner: root
    src: scripts/lab-destroy.j2
