- name: ensure services are loaded and active
  tags:
    - builder-services
    - builder-bootstrap
  service:
    enabled: yes
    name: "{{item}}"
    state: started
  loop:
    - libvirtd
    - docker
