- name: ensure services are loaded and active
  tags:
    - builder-services
    - builder-bootstrap
  service:
    enabled: true
    name: "{{item}}"
    state: started
  loop:
    - libvirtd

- name: ensure sshd does not rely on gssapi
  tags:
    - builder-services
    - builder-bootstrap
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^GSSAPIAuthentication yes$'
    replace: 'GSSAPIAuthentication no'
  register: sshd_config

- name: restart sshd upon config change
  tags:
    - builder-services
    - builder-bootstrap
  service:
    name: sshd
    state: restarted

- name: Ensure firewalld is active
  tags:
    - builder-services
    - builder-bootstrap
  when:
    - ansible_facts['distribution_version'] is version('8.0', 'gt', strict=False)
  service:
    name: firewalld.service
    state: started
    enabled: true
