---
- name: execute all as virt_user
  become: yes
  become_user: "{{ virt_user }}"
  tags:
    - images
    - undercloud
    - lab
  block:
    - name: install acpid only on centos
      set_fact: opt_pkg="--install acpid"
      when:
        - base_image == "centos"

    - name: undercloud image settings
      shell: |
        virt-sysprep -a "{{basedir}}/workload/undercloud.qcow2" \
          --firstboot-command "growpart /dev/sda 1" \
          --firstboot-command "xfs_growfs /dev/sda1" \
          --firstboot-command "systemctl enable acpid" \
          --firstboot-command "systemctl start acpid" \
          --firstboot-command "mkswap /dev/sdb" \
          --firstboot-command "swapon /dev/sdb" \
          --hostname undercloud.lain.internux.ch \
          --network {{ opt_pkg|default('') }} \
          --uninstall cloud-init \
          --selinux-relabel \
          --root-password "password:{{undercloud_password}}" \
          --ssh-inject root && \
          touch "{{basedir}}/workload/undercloud.qcow2.done"
      args:
        creates: "{{basedir}}/workload/undercloud.qcow2.done"

