---
- name: execute all as virt_user
  become: yes
  become_user: "{{ virt_user }}"
  block:
    - name: undercloud image settings
      tags:
        - images
        - undercloud
        - lab
      shell: |
        virt-sysprep -a "{{basedir}}/workload/undercloud.qcow2" \
          --firstboot-command "growpart /dev/sda 1" \
          --firstboot-command "xfs_growfs /dev/sda1" \
          --firstboot-command "systemctl enable acpid" \
          --firstboot-command "systemctl start acpid" \
          --hostname undercloud.lain.internux.ch \
          --network \
          --install acpid \
          --uninstall cloud-init \
          --selinux-relabel \
          --root-password "password:{{undercloud_password}}" \
          --ssh-inject root && \
          touch "{{basedir}}/workload/undercloud.qcow2.done"
      args:
        creates: "{{basedir}}/workload/undercloud.qcow2.done"
