- name: common tags
  tags:
    - vbmc
    - lab
    - builder-bootstrap
  block:
    - name: push virtualbmc script
      template:
        dest: /usr/local/sbin/vbmc-run
        src: vbmc-run.j2
        group: "{{virt_user}}"
        mode: 0750
        owner: root
      register: vbmc_script

    - name: create systemd unit file
      template:
        dest: /etc/systemd/system/vbmc.service
        src: vbmc.service.j2
        group: root
        mode: 0644
        owner: root
      register: install_vbmc_service

    - name: reload systemd daemon if vbmc.service changed
      command: systemctl daemon-reload
      when: install_vbmc_service is changed

    - name: register vbmc.service
      service:
        name: vbmc
        enabled: yes
        state: started

    - name: restart vbmc if script changed
      service:
        name: vbmc
        state: reloaded
      when: vbmc_script is changed

    - name: open firewall on libvirt link
      iptables:
        action: insert
        chain: INPUT
        comment: "allow vbmc access from undercloud"
        destination: "192.168.122.1"
        destination_port: "11200:11299"
        jump: ACCEPT
        protocol: udp
