---
- name: push deploy script
  template:
    dest: /home/stack/deploy.sh
    src: deploy.sh.j2
    mode: 0755
  vars:
    ip: '192.168.24.2'

- name: deploy standalone
  when: deploy_standalone|bool
  become: yes
  become_user: stack
  command: /home/stack/deploy.sh
  args:
    creates: /home/stack/install-standalone.log

- name: ensure we have a success
  command: grep -q 'Deployment Failed!' /home/stack/install-standalone.log
  ignore_errors: yes
  register: deploy_is_failed

- name: fail if deploy failed
  assert:
    that: deploy_is_failed.rc != 0
