---
- import_tasks: image-prepare.yaml
- import_tasks: ceph.yaml
- import_tasks: prepare.yaml
- import_tasks: deploy.yaml
- name: run tempest
  import_role:
    name: validations
    tasks_from: standalone
