---
- name: install lvm2 needed by cinder
  package:
    name: lvm2
    state: installed

- name: update containers-prepare push_destination
  replace:
    path: /home/stack/containers-prepare-parameter.yaml
    regexp: 'push_destination:.+'
    replace: "push_destination: 192.168.24.2:8787"

- name: basic parameters for standalone
  template:
    dest: /home/stack/standalone_parameters.yaml
    src: standalone_params.yaml.j2
  vars:
    ip: '192.168.24.2'
    interface: 'eth1'

- name: ceph params if requested
  when: standalone_ceph|bool
  copy:
    dest: /home/stack/ceph_parameters.yaml
    src: standalone_ceph.yaml

- name: octavia param
  copy:
    dest: /home/stack/octavia-param.yaml
    src: standalone_octavia.yaml
