---
- name: test endpoints
  shell: |
    export OS_CLOUD=standalone
    openstack endpoint list

- name: create tiny flavor
  shell: |
    export OS_CLOUD=standalone
    openstack flavor create --ram 512 --disk 1 --vcpu 1 --public tiny
