enable_metrics: false
overclouds: 1
vms:
  - name: undercloud
    cpu: 4
    memory: 16384
    interfaces:
      - network: default
      - Net2
    autostart: true
  - name: controller-0
    cpu: 2
    memory: 4096
    interfaces:
      - Net1
      - Net2
    autostart: false
  - name: controller-1
    cpu: 2
    memory: 4096
    interfaces:
      - Net1
      - Net2
    autostart: false
  - name: controller-2
    cpu: 2
    memory: 4096
    interfaces:
      - Net1
      - Net2
    autostart: false
  - name: compute-0
    cpu: 2
    memory: 4096
    interfaces:
      - Net1
      - Net2
    autostart: false
  - name: compute-1
    cpu: 2
    memory: 4096
    interfaces:
      - Net1
      - Net2
    autostart: false
  - name: ceph-0
    cpu: 2
    memory: 8192
    interfaces:
      - Net1
      - Net2
    autostart: false
  - name: ceph-1
    cpu: 2
    memory: 8192
    interfaces:
      - Net1
      - Net2
    autostart: false
  - name: ceph-2
    cpu: 2
    memory: 8192
    interfaces:
      - Net1
      - Net2
    autostart: false

virt_user: virtuser
basedir: "/home/{{virt_user}}"
undercloud_password: fooBar
centos_mirror: false
manage_mirror_device: true
mirror_base_directory: /srv/mirror
centos_mirror_device: /dev/sdc
base_image: centos
vm_prefix: lab
root_device: 1
growfs_part: /dev/sda1
guestfs_appliance: "appliance-1.38.0.tar.xz"
undercloud_python_interpreter: /usr/bin/python
undercloud_hostname: undercloud.localdomain
num_osds: 1
os_version: 7
