parameter_defaults:
  LocalCephAnsibleFetchDirectoryBackup: /root/ceph_ansible_fetch
  CephAnsibleDisksConfig:
    osd_objectstore: bluestore
    osd_scenario: lvm
    lvm_volumes:
      - data: ceph_lv_data
        data_vg: ceph_vg
        db: ceph_lv_db
        db_vg: ceph_vg
        wal: ceph_lv_wal
        wal_vg: ceph_vg
  CephPoolDefaultPgNum: 32
  CephPoolDefaultSize: 1
  CephAnsibleExtraConfig:
    centos_package_dependencies: []
    ceph_osd_docker_memory_limit: '1g'
    ceph_mds_docker_memory_limit: '1g'
    mon_host_v1: { 'enabled': False }
    handler_health_mon_check_retries: 10
    handler_health_mon_check_delay: 20
  CephAnsiblePlaybookVerbosity: 1
  CephAnsibleEnvironmentVariables:
    ANSIBLE_SSH_RETRIES: '4'
    DEFAULT_FORKS: '3'
