---
- name: fetch latest repo version
  shell: |
    curl -s https://trunk.rdoproject.org/centos7/current/ | awk '/python2-tripleo-repos/ { print $6}' | cut -d '"' -f 2
  register: tripleo_repo_version

- name: install tripleo repository
  package:
    name: "https://trunk.rdoproject.org/centos7/current/{{tripleo_repo_version.stdout}}"
    state: present

- name: enable tripleo_version repository with ceph
  command: tripleo-repos -b "{{tripleo_version}}" "{{ tripleo_mod }}" ceph
  args:
    creates: "/etc/yum.repos.d/delorean.repo"
