- name: set hostname properly
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 undercloud.{{ansible_domain}} undercloud localhost localhost.localdomain"
    regexp: '^127\.0\.0\.1'

- name: install tripleo repository
  yum:
    name: "https://trunk.rdoproject.org/centos7/current/{{tripleo_repo_version}}"
    state: present

- name: enable tripleo_version repository
  command: tripleo-repos -b "{{tripleo_version}}" current
  args:
    creates: "/etc/yum.repos.d/delorean-{{tripleo_version}}.repo"

- name: install some tools
  yum:
    name:
      - git
      - tmux
      - vim
    state: present

- name: do we have a swap file
  stat:
    path: /dev/sdb
  register: swap_on

- name: set fstab entry for swap if needed
  mount:
    backup: yes
    path: swap
    src: /dev/sdb
    state: present
    opts: defaults
    fstype: swap
  when:
    - swap_on.stat.exists
    - swap_on.stat.isblk

- name: install tripleo client
  yum:
    name: python-tripleoclient
    state: present
