---
- name: set hostname properly
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 undercloud.{{ansible_domain}} undercloud localhost localhost.localdomain"
    regexp: '^127\.0\.0\.1'

- name: install tripleo repository
  yum:
    name: "https://trunk.rdoproject.org/centos7/current/{{tripleo_repo_version}}"
    state: present

- name: enable tripleo_version repository
  command: tripleo-repos -b "{{tripleo_version}}" current

- name: install some tools
  yum:
    name: "{{item}}"
    state: present
  loop:
    - git
    - tmux
    - vim

- name: install tripleo client
  yum:
    name: python-tripleoclient
    state: present
