- name: install custom RPM from remote link
  yum:
    name: "{{ custom_rpms }}"
    state: installed
  when: custom_rpms | length > 0

- name: synchronize from controler to undercloud
  local_action:
    module: command
    _raw_params: "rsync -a --delete {{ item.base  }}/{{ item.name }} stack@undercloud:{{ item.dest | default(synchronize_default_dest) }}"
  loop: "{{ synchronize }}"
  loop_control:
    label: "{{ item.name }}"

- name: build synchronized packages
  become: yes
  become_user: stack
  loop: "{{ synchronize }}"
  loop_control:
    label: "{{ item.name }}"
  shell: |
    rm -rf tripleo/delorean/rdoinfo
    ./tripleo-ci/scripts/tripleo.sh --delorean-build {{ item.name }} > /home/stack/build_{{ item.name }}.log
    sudo rpm -Uvh --force $(find tripleo/delorean/ -name "*.rpm" -and -not -name "*.src.rpm")
  args:
    chdir: "/home/stack"

- name: build custom packages and install them
  become: yes
  become_user: stack
  when: ci_tools|bool
  loop: "{{ patches }}"
  loop_control:
    label: "{{ item.name }}"
  shell: |
    cd tripleo/
    rm -rf {{ item.name }} delorean/rdoinfo
    git clone https://github.com/openstack/{{ item.name }}
    cd {{ item.name }}
    git fetch https://git.openstack.org/openstack/{{ item.name }} refs/changes/{{ item.refs }}
    git checkout FETCH_HEAD
    cd /home/stack
    ./tripleo-ci/scripts/tripleo.sh --delorean-build {{ item.name }} > /home/stack/build_{{ item.name }}.log
    sudo rpm -Uvh --force $(find tripleo/delorean/ -name "*.rpm" -and -not -name "*.src.rpm")
  args:
    chdir: "/home/stack"
