- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: "deploy undercloud (explicit --use-heat)"
      when: use_heat|bool
      command: openstack undercloud install --use-heat
      args:
        creates: /home/stack/stackrc
        chdir: /home/stack

    - name: deploy undercloud
      when: not use_heat|bool
      command: openstack undercloud install
      args:
        creates: /home/stack/stackrc
        chdir: /home/stack
