---
- name: Ensure we have image-serve
  command: |
    ansible -m include_role \
      -a role=tripleo-image-serve \
      -e tripleo_container_registry_host='*' \
      localhost

- name: Ensure we have something for podman registry
  command: |
    ansible -m include_role \
      -a role=tripleo-podman \
      -e tripleo_container_registry_insecure_registries='["localhost","undercloud.ctlplane"]'
      localhost

- name: Ensure we have an entry for undercloud.ctlplane in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 undercloud.ctlplane undercloud.ctlplane.localdomain"
    state: present

- name: get standard container-prepare-image output
  shell: |
    openstack tripleo container image prepare default --local-push-destination
  register: container_image_prepare

- name: generate container-image-prepare
  template:
    src: containers-prepare-parameter.yaml.j2
    dest: /home/stack/containers-prepare-parameter.yaml
    owner: stack
    group: stack
  vars:
    content: "{{ modify_image|default([]) }}"

- name: run container image prepare if we have custom config
  when: modify_image|default([]) != []
  command: |
    openstack tripleo container image prepare \
    -e /home/stack/containers-prepare-parameter.yaml \
    --output-env-file /home/stack/generated-container-prepare.yaml

- name: Clean tweaked entry for undercloud.ctlplane in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 undercloud.ctlplane undercloud.ctlplane.localdomain"
    state: absent

