---
- name: Ensure we have image-serve
  command: |
    ansible -m include_role \
      -a role=tripleo-image-serve \
      -e tripleo_container_registry_host=undercloud.ctlplane.localdomain \
      localhost

- name: get standard container-prepare-image output
  shell: |
    openstack tripleo container image prepare default --local-push-destination
  register: container_image_prepare

- name: generate container-image-prepare
  template:
    src: containers-prepare-parameter.yaml.j2
    dest: /home/stack/containers-prepare-parameter.yaml
    owner: stack
    group: stack
  vars:
    content: "{{ modify_image|default([]) }}"

- name: run container image prepare if we have custom config
  when: modify_image|default([]) != []
  command: |
    openstack tripleo container image prepare \
    -e /home/stack/containers-prepare-parameter.yaml \
    --output-env-file /home/stack/generated-container-prepare.yaml
