---
- name: ensure we have RPMs to install
  find:
    path: /home/stack/custom-rpms/
    patterns: '*.rpm'
    recurse: false
  register: rpm_to_install

- name: install custom RPMs
  when: rpm_to_install['files'] !=  []
  command: "yum install -y {{ rpm_to_install['files'] |map(attribute='path') | join(' ') }}"

