- name: run on undercloud node
  tags:
    - undercloud-bootstrap
    - lab
  delegate_to: undercloud
  delegate_facts: false
  block:
    - import_tasks: config.yaml
    - import_tasks: rhos-release.yaml
    - import_tasks: packages.yaml
    - import_tasks: user.yaml
    - import_tasks: ci-tools.yaml
    - import_tasks: custom-packages.yaml
    - name: deploy standard undercloud and stuff
      when: not standalone|bool
      block:
        - import_tasks: prepare.yaml
        - name: deploy undercloud and prepare overcloud
          when:
            - deploy_undercloud|bool
          block:
            - import_tasks: deploy.yaml
            - import_tasks: overcloud.yaml
    - name: prepare and deploy standalone
      when: standalone|bool
      block:
        - name: go for standalone
          import_role:
            role: standalone
