- name: run on undercloud node
  tags:
    - undercloud-bootstrap
    - lab
  delegate_to: undercloud
  delegate_facts: false
  block:
    - import_tasks: config.yaml
    - import_tasks: user.yaml
    - import_tasks: rhos-release.yaml
    - import_tasks: rhel.yaml
    - name: install epel only on centos
      when: base_image == 'centos'
      import_tasks: epel.yaml
    - name: configure metrics
      when: enable_metrics|bool
      import_role:
        name: metrics
    - import_tasks: packages.yaml
    - name: deploy ci only on centos
      when: base_image == 'centos'
      import_tasks: ci-tools.yaml
    - name: custom packages only on centos
      when: base_image == 'centos'
      import_tasks: custom-packages.yaml
    - import_tasks: image-prepare.yaml
    - name: deploy standard undercloud and stuff
      when: not standalone|bool
      block:
        - import_tasks: prepare.yaml
        - name: deploy undercloud and prepare overcloud
          when:
            - deploy_undercloud|bool
          block:
            - import_tasks: deploy.yaml
            - name: run validations
              import_role:
                name: validations
                tasks_from: undercloud
            - import_tasks: overcloud.yaml
    - name: prepare and deploy standalone
      when: standalone|bool
      block:
        - name: go for standalone
          import_role:
            role: standalone
