---
- name: run on undercloud node
  tags:
    - undercloud-bootstrap
    - lab
  delegate_to: undercloud
  delegate_facts: false
  block:
    - import_tasks: config.yaml
    - import_tasks: rhos-release.yaml
    - import_tasks: packages.yaml
    - import_tasks: user.yaml
    - import_tasks: prepare.yaml
    - name: deploy undercloud and prepare overcloud
      when:
        - deploy_undercloud|bool
      block:
        - import_tasks: deploy.yaml
        - import_tasks: overcloud.yaml
        - import_tasks: ci-tools.yaml
