---
- name: run on undercloud node
  tags:
    - undercloud-bootstrap
  delegate_to: undercloud
  delegate_facts: false
  block:
    - import_tasks: config.yaml
    - import_tasks: user.yaml
    - import_tasks: prepare.yaml
