- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: fetch images
      tags:
        - baremetal
        - overcloud-images
      get_url:
        dest: "/home/stack/overcloud_imgs/{{item.file}}"
        url: "https://images.rdoproject.org/master/rdo_trunk/current-tripleo/{{item.file}}"
      loop: "{{ overcloud_images }}"
      loop_control:
        label: "{{item.file}}"

    - name: uncompress images
      tags:
        - baremetal
        - overcloud-images
      unarchive:
        creates: "/home/stack/overcloud_imgs/{{item.content}}"
        dest: "/home/stack/overcloud_imgs/"
        remote_src: yes
        src: "/home/stack/overcloud_imgs/{{item.file}}"
      loop: "{{ overcloud_images }}"
      loop_control:
        label: "{{item.file}}"

    # FIXME: Use os_image for these tasks
    - name: upload images to glance
      when: containerized_undercloud|bool
      tags:
        - baremetal
        - overcloud-images
      shell: |
        source ~/stackrc
        openstack overcloud image upload \
          --image-path /home/stack/overcloud_imgs \
          --http-boot /var/lib/ironic/httpboot \
          --update-existing

    - name: upload images to glance
      when: not containerized_undercloud|bool
      tags:
        - baremetal
        - overcloud-images
      shell: |
        source ~/stackrc
        openstack overcloud image upload \
          --image-path /home/stack/overcloud_imgs \
          --update-existing
