---
- name: install some tools
  yum:
    name: "{{item}}"
    state: present
  loop:
    - git
    - tmux
    - vim

- name: install tripleo client
  yum:
    name: python-tripleoclient
    state: present

