---
- name: update all packages
  yum:
    name: '*'
    state: latest

- name: install some tools
  yum:
    name: "{{item}}"
    state: present
  loop:
    - git
    - libguestfs-tools
    - tmux
    - vim

- name: install tripleo client
  yum:
    name: python-tripleoclient
    state: present

- name: install requested packages for ceph
  when: standalone_ceph|bool
  yum:
    name: [ceph-ansible, util-linux]
    state: installed

