---
- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: copy undercloud.conf sample
      copy:
        dest: /home/stack/undercloud.conf
        src: /usr/share/python-tripleoclient/undercloud.conf.sample
        remote_src: yes
    - name: generate baremetal.json file
      tags:
        - baremetal
      template:
        dest: /home/stack/baremetal.json
        mode: 0644
        src: baremetal.json.j2
    - name: prepare some scheduler hint ninja trick
      tags:
        - baremetal
      copy:
        dest: /home/stack/node-placement.yaml
        src: ../files/node-placement.yaml
    - name: create image directory
      tags:
        - baremetal
      file:
        path: "/home/stack/overcloud_imgs"
        state: directory
    - name: fetch images
      tags:
        - baremetal
      get_url:
        dest: "/home/stack/overcloud_imgs/{{item.file}}"
        url: "https://buildlogs.centos.org/centos/7/cloud/x86_64/tripleo_images/master/delorean/{{item.file}}"
      loop: "{{ overcloud_images }}"
      loop_control:
        label: "{{item.file}}"
    - name: uncompress images
      tags:
        - baremetal
      unarchive:
        creates: "/home/stack/overcloud_imgs/{{item.content}}"
        dest: "/home/stack/overcloud_imgs/"
        remote_src: yes
        src: "/home/stack/overcloud_imgs/{{item.file}}"
      loop: "{{ overcloud_images }}"
      loop_control:
        label: "{{item.file}}"
