- name: copy undercloud.conf sample
  copy:
    dest: /home/stack/undercloud.conf
    src: "{{ undercloud_sample }}"
    remote_src: yes
    owner: stack
    group: stack
    mode: 0640

- name: Enable masquerading in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: ctlplane-subnet
    option: masquerade
    value: true
    mode: 0640
    backup: yes

- name: Enable undercloud hieradata for low memory
  ini_file:
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: hieradata_override
    value: /home/stack/hieradata_undercloud_low_memory.yaml
    mode: 0640
    backup: yes
  when: undercloud_low_memory|bool

- name: Create hieradata_undercloud_low_memory.yaml
  template:
    dest: /home/stack/hieradata_undercloud_low_memory.yaml
    src: hieradata_undercloud_low_memory.yaml.j2
  when: undercloud_low_memory|bool

- name: custom configuration in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0640
    backup: yes
  loop: "{{ undercloud_config |default([])}}"
  loop_control:
    label: "{{ item.option }}"

- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: generate containers-prepare-parameter.yaml if using container
      when:
        - containerized_undercloud|bool
      args:
        creates: /home/stack/containers-prepare-parameter.yaml
      command: |
        openstack tripleo container image prepare default \
        --local-push-destination \
        --output-env-file /home/stack/containers-prepare-parameter.yaml
    - name: update registry if needed
      when:
        rhos_containers_registry != ''
      replace:
        path: /home/stack/containers-prepare-parameter.yaml
        regexp: "registry.access.redhat.com"
        replace: "{{ rhos_containers_registry }}"
    - name: generate baremetal.json file
      tags:
        - baremetal
      template:
        dest: /home/stack/baremetal.json
        mode: '0644'
        src: baremetal.json.j2
    - name: create overcloud-yml directory
      tags:
        - baremetal
      file:
        path: /home/stack/overcloud-yml
        state: directory
    - name: push overcloud settings
      tags:
        - baremetal
      copy:
        dest: /home/stack/overcloud-yml/
        src: "{{ item }}"
      with_fileglob: 'files/overcloud/*.yaml'
    - name: push scale setting
      tags:
        - baremetal
      template:
        dest: /home/stack/overcloud-yml/scale.yaml
        src: scale.yaml.j2
    - name: push ceph settings
      tags:
        - baremetal
      template:
        dest: /home/stack/overcloud-yml/ceph-params.yaml
        src: ceph-params.yaml.j2
    - name: push container-cli setting
      tags:
        - baremetal
      template:
        dest: /home/stack/overcloud-yml/container-cli.yaml
        src: container-cli.yaml.j2
    - name: push basic deploy script
      tags:
        - baremetal
      template:
        dest: /home/stack/deploy-overcloud.sh
        src: overcloud-deploy.sh.j2
        mode: 0750
    - name: create image directory
      tags:
        - baremetal
        - overcloud-images
      file:
        path: "/home/stack/overcloud_imgs"
        state: directory
