- name: copy root authorized_keys to stack user
  copy:
    dest: /home/stack/.ssh/authorized_keys
    group: stack
    mode: '0644'
    owner: stack
    remote_src: yes
    src: /root/.ssh/authorized_keys

- name: copy undercloud.conf sample
  copy:
    dest: /home/stack/undercloud.conf
    src: "{{ undercloud_sample }}"
    remote_src: yes
    owner: stack
    group: stack
    mode: 0640

- name: Enable masquerading in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: ctlplane-subnet
    option: masquerade
    value: true
    mode: 0640
    backup: yes

- name: custom configuration in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0640
    backup: yes
  loop: "{{ undercloud_config |default([])}}"
  loop_control:
    label: "{{ item.option }}"

- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: generate baremetal.json file
      tags:
        - baremetal
      template:
        dest: /home/stack/baremetal.json
        mode: '0644'
        src: baremetal.json.j2
    - name: create overcloud-yml directory
      tags:
        - baremetal
      file:
        path: /home/stack/overcloud-yml
        state: directory
    - name: push overcloud settings
      tags:
        - baremetal
      copy:
        dest: /home/stack/overcloud-yml/
        src: "{{ item }}"
      with_fileglob: 'files/overcloud/*.yaml'
    - name: push scale setting
      tags:
        - baremetal
      template:
        dest: /home/stack/overcloud-yml/scale.yaml
        src: scale.yaml.j2
    - name: push basic deploy script
      tags:
        - baremetal
      copy:
        dest: /home/stack/deploy-overcloud.sh
        src: overcloud/deploy.sh
        mode: 0750
    - name: create image directory
      tags:
        - baremetal
        - overcloud-images
      file:
        path: "/home/stack/overcloud_imgs"
        state: directory
