---
- name: copy root authorized_keys to stack user
  copy:
    dest: /home/stack/.ssh/authorized_keys
    group: stack
    mode: 0644
    owner: stack
    remote_src: yes
    src: /root/.ssh/authorized_keys

- name: copy undercloud.conf sample
  copy:
    dest: /home/stack/undercloud.conf
    src: "{{ undercloud_sample }}"
    remote_src: yes
    owner: stack
    group: stack
    mode: 0640
- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: generate baremetal.json file
      tags:
        - baremetal
      template:
        dest: /home/stack/baremetal.json
        mode: 0644
        src: baremetal.json.j2
    - name: create overcloud-yml directory
      tags:
        - baremetal
      file:
        path: /home/stack/overcloud-yml
        state: directory
    - name: push domain configuration
      tags:
        - baremetal
      copy:
        dest: /home/stack/overcloud-yml/domain.yaml
        src: ../files/overcloud/domain.yaml
    - name: push scheduler hint ninja trick
      tags:
        - baremetal
      copy:
        dest: /home/stack/overcloud-yml/node-placement.yaml
        src: ../files/overcloud/node-placement.yaml
    - name: push network settings
      tags:
        - baremetal
      copy:
        dest: /home/stack/overcloud-yml/network.yaml
        src: ../files/overcloud/network.yaml
    - name: push basic deploy script
      tags:
        - baremetal
      copy:
        dest: /home/stack/overcloud-deploy.sh
        src: ../files/overcloud/deploy.sh
        mode: 0750

    - name: create image directory
      tags:
        - baremetal
        - overcloud-images
      file:
        path: "/home/stack/overcloud_imgs"
        state: directory
