---
- name: copy root authorized_keys to stack user
  copy:
    dest: /home/stack/.ssh/authorized_keys
    group: stack
    mode: 0644
    owner: stack
    remote_src: yes
    src: /root/.ssh/authorized_keys

- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: copy undercloud.conf sample
      copy:
        dest: /home/stack/undercloud.conf
        src: /usr/share/python-tripleoclient/undercloud.conf.sample
        remote_src: yes
    - name: generate baremetal.json file
      tags:
        - baremetal
      template:
        dest: /home/stack/baremetal.json
        mode: 0644
        src: baremetal.json.j2
    - name: prepare some scheduler hint ninja trick
      tags:
        - baremetal
      copy:
        dest: /home/stack/node-placement.yaml
        src: ../files/node-placement.yaml
    - name: create image directory
      tags:
        - baremetal
        - overcloud-images
      file:
        path: "/home/stack/overcloud_imgs"
        state: directory
