---
- name: Some hacks specificy for RHEL
  when: base_image == 'rhel'
  block:
    - name: "unmanage {{ unmanage_iface }}"
      command: nmcli dev set {{ unmanage_iface }} managed no

    - name: ensure we do have DNS resolution
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 1.1.1.1
          nameserver 8.8.8.8

    - name: install some packages
      package:
        name:
          - iptables-services
          - network-scripts

    - name: some hiera override
      copy:
        dest: /home/stack/undercloud_hiera.yaml
        content: |
          glance_backend: 'file'
          tripleo::profile::base::nova::enable_cache: false
        owner: stack
        group: stack
