- name: create stack user
  user:
    comment: "Stack user for tripleo"
    create_home: yes
    generate_ssh_key: yes
    name: stack
    shell: "/bin/bash"
    ssh_key_bits: 4096
    state: present

- name: give sudo accesses
  tags:
    - sudo
  copy:
    dest: /etc/sudoers.d/stack
    src: stack.sudoers
    group: root
    mode: '0440'
    owner: root
