---
virt_user: virtuser
tripleo_version: rocky
overcloud_images:
  - file: ironic-python-agent.tar
    content: ironic-python-agent.kernel
  - file: overcloud-full.tar
    content: overcloud-full.qcow2

containerized_undercloud: yes
ci_tools: yes
deploy_undercloud: yes
undercloud_sample: /usr/share/python-tripleoclient/undercloud.conf.sample
undercloud_dns: 192.168.122.1
